version: '3'

services:

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./db:/app/db 
    environment:
      - DB_PATH=/app/db/bans.db
    restart: always



